### PR TITLE
Try to fix on Unix line endings

### PR DESCRIPTION
**Pull request by johnnyreilly**
LF FTW!

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Looks good. You happy with this @blakeembrey?

**Comment by johnnyreilly** [comment]
Ah really - what's the bug?

**Comment by blakeembrey** [comment]
I'm normalizing line endings of content that is transformed (E.g. we wrap things, etc) but I forgot to normalize endings of ambient definitions. https://github.com/typings/core/blob/master/src/lib/compile.ts#L444

**Comment by johnnyreilly** [comment]
Gotcha

**Pull request closed without merging**
