### PR TITLE
Normalize all EOL to `\n`, normalize slashes

### PR DESCRIPTION
**Pull request by blakeembrey**
Related to https://github.com/typings/core/pull/39.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
This makes me so happy: 

screenshot 2016-03-10 05 25 31

Well done @blakeembrey!

**Comment by johnnyreilly** [comment]
Although I'm still getting 1 failing test when I run locally:

```
  compile inline ambient definitions
    √  should be equal
    ×  should be equal at undefined
        '// Generated by typings\n// Source: __test__/fixtures/compile-inline-ambient/node.d.ts\ndeclare const require:
(module: string) => any;\r\n\r\ndeclare module "events" {\r\n\texport const test: boolean;\r\n}\r\n\r\ndeclare module "f
s" {\r\n\timport * as events from "events";\r\n}'
```

It's this [one](https://github.com/typings/core/blob/master/src/lib/compile.spec.ts#L379):

```
    t.test('compile inline ambient definitions', t => {
      const FIXTURE_DIR = join(FIXTURES_DIR, 'compile-inline-ambient')
      const typings = join(FIXTURE_DIR, 'node.d.ts')

      const node: DependencyTree = {
        src: __filename,
        raw: undefined,
        postmessage: undefined,
        ambient: true,
        typings,
        dependencies: {},
        devDependencies: {},
        peerDependencies: {},
        ambientDependencies: {},
        ambientDevDependencies: {}
      }

      const emitter = new EventEmitter()

      return compile(node, { name: 'name', cwd: __dirname, ambient: true, meta: true, emitter })
        .then(result => {
          const contents = [
            `// Generated by typings`,
            `// Source: __test__/fixtures/compile-inline-ambient/node.d.ts`,
            'declare const require: (module: string) => any;',
            '',
            'declare module "events" {',
            '\texport const test: boolean;',
            '}',
            '',
            'declare module "fs" {',
            '\timport * as events from "events";',
            '}'
          ].join('\n')

          t.equal(result.main, result.browser)
          t.equal(result.main, contents) // HELLO HOUSTON!  I AM A PROBLEM
        })
    })
  })
```

**Comment by johnnyreilly** [comment]
This was the ts-loader issue I was alluding to earlier: https://github.com/TypeStrong/ts-loader/issues/136#issuecomment-174210506 

It may provide insight

**Comment by johnnyreilly** [comment]
Would it be worth making [these changes](https://github.com/TypeStrong/ts-loader/commit/2c197dfbcb192fe471e5d0106ddfca3116de7656) to the `.gitattributes`:

```
*.ts eol=lf
*.js eol=lf
```

**Comment by unional** [comment]
I would say everything `LF` :stuck_out_tongue:

**Comment by johnnyreilly** [comment]
Looks good on my machine guys: https://github.com/typings/core/pull/45

Just need to check that the CI builds are still happy....

**Pull request merged**
