### PR TITLE
Consider ambient

### PR DESCRIPTION
**Pull request by unional**
Fixes https://github.com/typings/typings/issues/535

### CODE REVIEW

**Comment by unional** [comment]
The build on node 0.10 is not stable. Failed one and success on the other.

**Comment by blakeembrey** [comment]
I think the builds can be occasionally buggy. Not sure though, I've seen an occasional failure too.

Do you think this is a better approach than just updating the source? The usefulness of that flag has never been major. It's really only for immediate feedback and used in only one place. I think I'd prefer we use `config.global` directly and then, when serialised, the `global` flag will be undefined (hence not serialised).

**Comment by blakeembrey** [comment]
Actually, let's do that - let's just not use the flag unless it's a boolean. Something like `typeof config.global === 'boolean' ? config.global : undefined`.

**Comment by unional** [comment]
Done :smile:

**Pull request merged**
