### PR TITLE
Make test-spec run tests on Windows again

### PR DESCRIPTION
**Pull request by johnnyreilly**
To resolve https://github.com/typings/core/issues/38

### CODE REVIEW

**Comment by unional** [comment]
Seems like need to do the same thing for `test-cov`

**Comment by johnnyreilly** [comment]
Yup - there's also 3 failing tests on windows which I'll look at when i get a mo:

```
  bundle everything
    ×  should be equal at undefined
        '// Generated by typings\r\n// Source: custom_typings\\/test.d.ts\r\ndeclare module \'~example~test\' {\r\nexpor
t function test (): string;\r\n}\r\n\r\n// Generated by typings\r\n// Source: index.d.ts\r\ndeclare module \'~example/in
dex\' {\r\nexport { test } from \'~example~test\'\r\n}\r\ndeclare module \'example/index\' {\r\nexport * from \'~example
/index\';\r\n}\r\ndeclare module \'example\' {\r\nexport * from \'~example/index\';\r\n}\r\n'

  install everything
    ×  should be equal at undefined
        '/// <reference path="main\\/ambient\\/test\\/index.d.ts" />\r\n/// <reference path="main\\/definitions\\/test\\
/index.d.ts" />\r\n'
    ×  should be equal at undefined
        '/// <reference path="browser\\/ambient\\/test\\/index.d.ts" />\r\n/// <reference path="browser\\/definitions\\/
test\\/index.d.ts" />\r\n'
    √  should be equal
    √  should be equal
    √  should be equal
```

**Comment by johnnyreilly** [comment]
Is it deliberate that `npm run test-spec` isn't part of `npm run test` @blakeembrey? (Apologies if I've already asked that) it seems like it should be part....

**Comment by unional** [comment]
Is it because `test-cov` already cover `test-spec`?

**Comment by johnnyreilly** [comment]
Oh does it? Missed that. Maybe if I flip the single quotes for doubles I'll get that. Never seen coverage working on windows. Ideally I'd like it to. But as a minimum I want to get the test specs running cross platform. (Since coverage will not be affected by the platform at all I think it's fine for it to run only on Travis; just as long as it runs somewhere that's fine)

**Comment by blakeembrey** [comment]
Nice catch, sorry! I completely glossed over the fact no tests actually run. I thought single quotes would work on PowerShell, but I'm completely up in the air about Windows things. I'll try switching them to double quotes and fixing the tests too.

**Comment by blakeembrey** [comment]
Merged with https://github.com/typings/core/commit/24d8a88daa93dd5b20b7c444bf441ab851971c7d

**Comment by blakeembrey** [comment]
@johnnyreilly What's preferred usually? Should we normalize all new lines to `\n` or `os.EOL`?

**Comment by johnnyreilly** [comment]
Um this came up recently when we were doing some cross platform stuff for ts-loader. I think we settled on `os.EOL`. @jbrantly can you remember?

**Comment by blakeembrey** [comment]
I remember there was that issue about cross-platform development too. If we settle on `\n` it'll solve that issue technically.

**Comment by johnnyreilly** [comment]
Hmmm... tests failing on AppVeyor now. Shall we drop coverage for now on AppVeyor and just have `test-spec` being run? I can tweak the appveyor.yml to do that.

**Comment by blakeembrey** [comment]
Sorry, I've got it passing in another branch. It was just deciding which approach to Windows compat we wanted - `os.EOL` or `\n`.

**Comment by johnnyreilly** [comment]
Ah great!  I don't have a strong opinion; whatever floats your boat :boat:

**Pull request closed without merging**
