### PR TITLE
Switch to using excludes for compilation

### PR DESCRIPTION
**Pull request by blakeembrey**

### CODE REVIEW

**Comment by unional** [comment]
Looks cool! And it works well for this case because you put source and test files together under `src` 😄  👍

**Comment by blakeembrey** [comment]
Haha, thanks - I've been doing that on most my projects, easier to manage transpiling with it all under the one directory.

**Comment by unional** [comment]
One questions: How does `tsc` knows in this case that `typings.ts` is the main file? Does it read `package.json`?

**Comment by blakeembrey** [comment]
It doesn't care, it'll traverse all `*.{ts,tsx}` files and transpile them.

**Pull request merged**
