### PR TITLE
Fix resolution of dependencies for barrels

### PR DESCRIPTION
**Pull request by Delagen**

### CODE REVIEW

**Comment by blakeembrey** [comment]
Unfortunately this introduces synchronous code into the processing stack, which I'd prefer to avoid. It also won't work when installing from a non-local file (which occurs 90% of the time). Thanks for putting together the PR though and showing your interest! I can either look at making a more permanent PR (probably by instead attempting the requests in a loop) or you're free to update this PR.

**Comment by Delagen** [comment]
All tests passed. If you don't cover 90% of the time function your tests is for mark only.

**Comment by blakeembrey** [comment]
I don't understand what your comment is in reference to, but of course they pass. Your code is doing the same thing, but as I mentioned, you've now introduced synchronous code into the stack. Please don't.

**Comment by blakeembrey** [comment]
It's also a good point, you should add tests to make sure the new code actually works. Can you add a test for the `index.d.ts` resolution?

**Comment by unional** [comment]
I think he means the 90% use case (installing from non-local file) is not covered by the current tests.

Which is true, however it depends on how much work is needed to stub popsicles and simulate the results.

**Comment by blakeembrey** [comment]
Oh, gotcha, we should fix that up. It's only a few lines of code though since those routes work similarly across FS and HTTP. However, that doesn't discount the main issue which is that this code is using a synchronous method from TypeScript.

**Comment by Delagen** [comment]
Premature optimization is the root of all evil in module which executed 1.5 times per project lifetime

**Comment by blakeembrey** [comment]
@Delagen Please stop speaking in half-quotes, it's difficult to understand what you're saying. This isn't premature optimisation, this is an extremely simple request to write something the correct way instead of the wrong way. If I were to merge this, it'd cause simple things like the Typings CLI spinner to be blocked from rendering while the module resolves because it's synchronous.

**Comment by unional** [comment]
Also, each open source project have certain expectations and guidelines on how the code should be written.

As we contribute to open source projects, we should follow the coding style and design patterns used in the project.

Thanks.

**Comment by Delagen** [comment]
Execution time of TS resolve method:
generally 0.2 - 0.5 ms per call, and up to 5-6 ms when resolution fails
As for me it has no impact any spinner rendering in 99.99% case
To delay bundle up to 0.5s it must process minimum 100 definition files. Only few projects have this number of files

**Comment by blakeembrey** [comment]
Yes, but those methods are not IO bound. Just because you have fast filesystem access it doesn't apply to others. I'm going to close this PR as it's taking too much back and forth and you don't appear to want to fix it. Thanks for giving it a shot anyway!

**Comment by blakeembrey** [comment]
So I spent a few hours on fixing this and unfortunately it's a more complex fix than I had hoped. This change doesn't do the half of what's needed and re-factored **a lot** to make it work. For instance, the primary issue is that this doesn't actually re-map any of the imports. So even if you do map from `x` to `x/index`, you need to be able to use that to re-calculate both the **import** and the **declare** module names - this doesn't do that and neither did my work today.

**Comment by Delagen** [comment]
Sad to notice, but my solution works better.
Try to bundle typings of `@angular/core` package. Your solution emit full path to typings in bundle.
Latest 2.3.1 version even emit cannot read `modulePath` of undefined.

**Comment by blakeembrey** [comment]
@Delagen Then help fix it. Your solution was not "better", it was broken. If you had helped at all, maybe it could have been a better solution. A "better" solution is not one that works for just you and that no one else will maintain, it's a solution that works for everyone and everyone can improve.

**Comment by blakeembrey** [comment]
@Delagen I just tested it and it seemed to work fine. I don't get any full paths or `undefined` issues. Can you share the issue you're running into? Perhaps you ran into https://github.com/typings/core/pull/173?

**Comment by Delagen** [comment]
@blakeembrey If my solution is broken. Why it produced 100% the same bundles in 99%, and different in case your solution provides broken?

```
npm i typings -g
npm i @angular/core@next
cd node-modules/@angular/core
typings bundle -out bundle.d.ts
```
Cause error
```
typings ERR! message Cannot read property 'modulePath' of undefined
typings ERR!
typings ERR! cwd C:\12341234\node_modules\@angular\core
typings ERR! system Windows_NT 10.0.15031
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\12341234\\node_modules\\typings\\dist\\bin.js" "bundle"
"-out" "bundle.d.ts"
typings ERR! node -v v7.6.0
typings ERR! typings -v 2.1.0
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```
if downgrade typings-core to 2.3.0
```
C:\12341234\node_modules\@angular\core>..\..\.bin\typings bundle -out aaa.d.ts
typings ERR! message EISDIR: illegal operation on a directory, open 'C:\12341234\node_modules\@angular\core'
typings ERR!
typings ERR! cwd C:\12341234\node_modules\@angular\core
typings ERR! system Windows_NT 10.0.15031
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\12341234\\node_modules\\typings\\dist\\bin.js" "bundle"
"-out" "aaa.d.ts"
typings ERR! node -v v7.6.0
typings ERR! typings -v 2.1.0
typings ERR! code EISDIR
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```
if i call it through api it works (but only with 2.3.0), but full path in definition at line 2457 for 4.0.0-rc.1 version of `@angular/core`
```
import { DebugContext } from 'C:\...\node_modules\@angular\core\typings\src\view';
```

**Comment by blakeembrey** [comment]
@Delagen I'm not spending anymore time on this discussion, sorry. I've said it half a dozen times now and it's extremely counterproductive for myself to continue engaging in this discussion with you. If I had spent all the time on this issue instead creating a solution, I probably could have been done with it already. If you're too stubborn to understand what it means to contribute productively to OSS, that's fine too.

Thanks for the report, I will look into it, but I won't be responding anymore. If you wanted to help, feel free to submit a productive PR.

**Comment by blakeembrey** [comment]
So it was a really easy fix - just check if `moduleInfo` was defined. I just made a PR and will merge and release it. This is what contributing productively can look like - you pointed out the issue and we've resolved it quickly. That's a little different to how this PR went, where instead you refused to help or fix the core issues. If you didn't have the bandwidth or know-how to make that work, it's completely understandable, the code is pretty complex to follow (hence a couple of bugs appearing even after I implemented it) - but at least accept that and let me know.

**Pull request closed without merging**
